// ============================================
// LANGUAGE SELECTION & TRANSLATION SYSTEM
// ============================================

// Current language (default: English)
let currentLanguage = localStorage.getItem('bharatfarm_language') || 'en';

// Translations object (from your HTML file)
const translations = {
    en: {
        loading_subtitle: "Preparing your smart farming dashboard...",
        login_tagline: "Your smart farming companion for better crop planning and higher productivity",
        welcome_back: "Welcome Back", 
        login_subtitle: "Login to access your farming dashboard",
        my_cart: "My Cart",
        cart_empty: "Your cart is empty",
        farming_history: "Farming History",
        preferred_crops: "Preferred Crops",
        footer_platform: "Platform",
        footer_links: "Other Links",
        footer_legal: "Legal",
        footer_about: "About",
        feat_ai_assistant: "AI Farming Assistant",
        feat_smart_market: "Smart Marketplace",
        feat_disease_scanner: "AI Disease Scanner",
        feat_weather: "Weather Monitoring",
        feat_cost_calc: "Cost Calculator",
        feat_activity_roadmap: "Activity Roadmap",
        select_language: "Select Language",
        schemes_step1_note: "Enter 0 if you are a landless farmer or sharecropper.",
        click_upload: "Click to upload or drag and drop an image",
        analyzing_leaf: "Analyzing leaf image...",
        humidity_label: "Humidity",
        wind_speed_label: "Wind Speed",
        visibility_label: "Visibility",
        weather_suitable: "Weather conditions are suitable for farming activities.",
        prev_page: "Previous",
        next_page: "Next",
        climate_req: "Climate Requirement",
        generating_insights: "Generating AI insights...",
        select_land_unit: "Select Land Unit",
        revenue_explanation: "Select a crop and enter land size to see your expected revenue.",
        quiz_loading_q: "Loading question...",
        login: "Login", 
        register: "Register", 
        phone_number: "Phone Number", 
        password: "Password",
        full_name: "Full Name", 
        confirm_password: "Confirm Password", 
        logout: "Logout",
        dashboard: "Dashboard", 
        leaf_scanner: "Leaf Scanner", 
        weather: "Weather", 
        crops: "Crops",
        calculator: "Calculator", 
        roadmap: "Roadmap", 
        alerts: "Alerts", 
        welcome: "Welcome",
        dashboard_subtitle: "Your smart farming companion for better crop planning",
        weather_status: "Weather", 
        scan_now: "Scan Now", 
        detect_disease: "Detect Disease",
        next_activity: "Next Activity", 
        view_roadmap: "View Roadmap", 
        input_cost: "Input Cost",
        calculate: "Calculate", 
        revenue: "Revenue", 
        view_details: "Details",
        quick_tips: "Quick Tips for Today", 
        get_started: "Get Started", 
        scan_leaf: "Scan Leaf",
        check_weather: "Check Weather", 
        select_crop: "Select Crop", 
        calculate_costs: "Calculate Costs",
        leaf_disease_scanner: "Leaf Disease Scanner",
        scanner_desc: "Upload or capture a photo of any plant leaf to detect diseases and get fertilizer recommendations.",
        upload_leaf: "Upload Leaf Image", 
        click_or_drag: "Click to upload or drag and drop",
        take_photo: "Take Photo", 
        browse_files: "Browse Files", 
        analyze_leaf: "Analyze Leaf",
        analyzing: "Analyzing leaf image...", 
        enter_location: "Enter Your Location",
        get_weather: "Get Weather", 
        rain_probability: "Rain", 
        humidity: "Humidity", 
        wind: "Wind",
        visibility: "Visibility", 
        safe_farming: "SAFE for Farming",
        safe_msg: "Weather conditions are suitable for farming activities.",
        unsafe_farming: "NOT SAFE for Farming",
        unsafe_msg: "High rain probability. Avoid fertilizer application.",
        crop_desc: "Choose a crop to see detailed farming recommendations.",
        crop_info: "Crop Info", 
        duration: "Duration", 
        watering: "Watering", 
        fertilizers: "Fertilizers",
        schedule: "Schedule", 
        cost_calculator: "Seed & Fertilizer Cost Calculator",
        cost_note: "Only seed & fertilizer costs. 2024 India market rates.",
        land_unit: "Select Land Unit", 
        land_size: "Land Size", 
        cost_breakdown: "Cost Breakdown",
        seed_qty: "Seed Quantity", 
        seed_cost: "Seed Cost", 
        fert_qty: "Fertilizer Quantity",
        fert_cost: "Fertilizer Cost", 
        total_cost: "TOTAL INPUT COST",
        revenue_prediction: "Revenue Prediction", 
        expected_revenue: "Expected Revenue",
        revenue_note: "Select a crop and enter land size to see your expected revenue.",
        expected_yield: "Expected Yield", 
        market_price: "Market Price", 
        profit_margin: "Profit Margin",
        crop_roadmap: "Crop Activity Roadmap", 
        select_crop_first: "Select a crop to view schedule",
        select_crop_roadmap: "Please select a crop first to generate roadmap.",
        notifications: "Notifications & Alerts",
        tip_morning: "Morning: Best time for watering - reduces evaporation.",
        tip_afternoon: "Afternoon: Inspect crops for pests during warm hours.",
        tip_evening: "Evening: Apply fertilizers for better absorption.",
        healthy_plant: "Healthy Plant", 
        disease_detected: "Disease Detected",
        recommended_fertilizers: "Recommended Fertilizers", 
        treatment_tips: "Treatment Tips",
        // Crop section
        crop_search_placeholder: "Search crops (e.g., Tomato, Rice...)",
        crop_search_desc: "Search for any crop to see detailed farming recommendations from the global database.",
        cat_all: "All",
        cat_cereal: "Cereal",
        cat_vegetable: "Vegetable",
        cat_fruit: "Fruit",
        cat_oilseed: "Oilseed",
        searching_crops: "Searching crop database...",
        no_crops_found: "No crops found matching your search. Try a different name or category.",
        previous: "Previous",
        next: "Next",
        scientific_name: "Scientific Name",
        climate_requirement: "Climate Requirement",
        soil_type: "Soil Type",
        total_duration: "Total Duration",
        water_requirement: "Water Requirement",
        harvesting_period: "Harvesting Period",
        ai_insights: "AI Growing Insights",
        view_roadmap_btn: "View Roadmap",
        calculate_costs_btn: "Calculate Costs",
        crop_info_label: "Crop Information",
        cropNames: {
            tomato: "Tomato", potato: "Potato", onion: "Onion", carrot: "Carrot",
            cabbage: "Cabbage", spinach: "Spinach", brinjal: "Brinjal (Eggplant)",
            cauliflower: "Cauliflower", okra: "Okra (Lady's Finger)", capsicum: "Capsicum (Bell Pepper)",
            mango: "Mango", banana: "Banana", apple: "Apple", papaya: "Papaya",
            guava: "Guava", orange: "Orange", grapes: "Grapes", pomegranate: "Pomegranate",
            watermelon: "Watermelon", pineapple: "Pineapple",
            rice: "Rice", wheat: "Wheat", maize: "Maize (Corn)", barley: "Barley", oats: "Oats",
            mustard: "Mustard", soybean: "Soybean", sunflower: "Sunflower", groundnut: "Groundnut (Peanut)"
        },
        categoryNames: {
            vegetable: "VEGETABLE", fruit: "FRUIT", cereal: "CEREAL", oilseed: "OILSEED"
        },
        // Schemes
        schemes_title: "Government Scheme Matchmaker",
        schemes_subtitle: "Find government schemes & subsidies you are eligible for",
        schemes_step1_title: "Farm Size",
        schemes_step1_label: "How much land do you farm?",
        schemes_step1_placeholder: "Enter land size in acres",
        schemes_step2_title: "Your State",
        schemes_step2_label: "Select your state",
        schemes_step2_placeholder: "-- Select State --",
        schemes_step3_title: "Main Crop",
        schemes_step3_label: "What is your main crop?",
        schemes_step3_placeholder: "e.g. Rice, Wheat, Tomato...",
        schemes_prev: "Previous",
        schemes_next: "Next",
        schemes_find: "Find My Schemes",
        schemes_finding: "Finding Schemes...",
        schemes_back: "Search Again",
        schemes_eligible: "Eligible Schemes",
        schemes_matched: "Schemes Matched",
        schemes_empty_title: "No Schemes Found",
        schemes_empty_msg: "We couldn't find any specific schemes matching your profile. Check back later or adjust your inputs.",
        schemes_try_again: "Try Again",
        schemes_eligibility: "Eligibility",
        schemes_benefits: "Benefits / Profit",
        schemes_apply: "Apply Now",
        schemes_any_size: "Any Size",
        schemes_all_states: "All States",
        schemes_all_crops: "All Crops",
        schemes_central: "Central",
        schemes_state: "State",
        schemes_centralstate: "Central/State",
        marketplace_title: "Marketplace",
        marketplace_label: "Buy & Sell",
        marketplace_status: "Open",
        schemes_title_short: "Govt Schemes",
        schemes_check_eligibility: "Check Eligibility",
        schemes_matchmaker: "Matchmaker",
        premium_marketplace: "AI-Driven Marketplace",
        premium_trade: "Direct-to-Buyer Trade",
        premium_commission: "Zero Commission Sales",
        premium_leaf_scanner: "Leaf Disease Scanner",
        premium_roadmap: "Farming Activity Roadmap",
        premium_weather: "Advanced Weather Alerts",
        premium_revenue: "Revenue Predictions",
        premium_support: "Priority Support",
        premium_ad_free: "Ad-free Experience",
        premium_plan_title: "Choose Your Farming Plan",
        premium_plan_subtitle: "Unlock advanced tools to maximize your yield",
        premium_free_month: "1st month is FREE for all new users!",
        free_version: "Free Version",
        free_dashboard: "Basic Dashboard",
        free_weather: "Weather Updates",
        free_calculator: "Cost Calculator",
        free_marketplace: "Browse Marketplace",
        free_roadmap: "Detailed Activity Roadmap",
        free_support: "Expert Support",
        schemes_loading_msg_1: "Helping our Annadata... Finding the best government schemes for your prosperity.",
        schemes_loading_msg_2: "Sowing the seeds of information... Fetching the latest updates for your farm.",
        // Redesigned Dashboard Keys
        hero_title: "Your AI Companion for",
        hero_accent: "Smarter Farming",
        hero_sub: "Welcome, <strong><span id=\"welcomeName\">Farmer</span></strong>! Empowering Indian agriculture with real-time intelligence, voice-first assistance, and direct market access.",
        hero_get_started: "Get Started",
        hero_explore: "Explore Ecosystem",
        float_weather_label: "Weather Alert",
        float_activity_label: "Next Activity",
        float_activity_value: "Select crop",
        float_roadmap_status: "View Roadmap",
        ecosystem_tag: "THE ECOSYSTEM",
        ecosystem_title: "Cultivating the Future",
        kb_title: "KrishiBot: Voice First AI",
        kb_desc: "Talk to your farm. Get advice in your local dialect on irrigation, pest control, and market trends.",
        kb_cta: "Talk Now",
        ls_title: "Leaf Scanner",
        ls_desc: "Instant Gemini-powered crop disease diagnosis from a single photograph.",
        ls_cta: "Launch Scan",
        sm_title: "Smart Market",
        sm_desc: "Sell direct to urban clusters. Cut the middleman.",
        sm_cta: "Open Market",
        ha_title: "Hyperlocal Analytics",
        ha_desc: "Soil moisture, nutrient levels, and precision weather forecasting for your specific coordinates.",
        ha_input_label: "Input Cost",
        ha_revenue_label: "Revenue",
        gs_title: "Govt Schemes",
        gs_desc: "Check eligibility for PM-KISAN, PMFBY, and state-specific subsidies.",
        gs_cta: "Matchmaker",
        impact_title: "From Soil to Soul.",
        impact_desc: "We don't just provide data; we provide a bridge between the hardworking farmer and the conscious consumer. Join an ecosystem that respects the land and rewards the labor.",
        impact_stat1_title: "Sustainability First",
        impact_stat1_desc: "Reducing fertilizer waste by 30% through AI precision",
        impact_stat2_title: "Fair Pricing",
        impact_stat2_desc: "Direct distribution ensures farmers get 85% of retail price",
        // Marketplace & Header
        header_premium: "Premium",
        header_logout: "Logout",
        mk_browse: "Browse Market",
        mk_sell: "Sell Produce",
        mk_role_buyer: "Buyer",
        mk_role_farmer: "Farmer",
        mk_switch_role: "Switch Role",
        mk_search_placeholder: "Search crops, farmers or regions...",
        mk_add_listing: "Add New Listing",
        mk_product_name: "Product Name",
        mk_crop_placeholder: "Type or select a crop...",
        mk_category: "Category",
        mk_price: "Price (Rs.)",
        mk_unit: "Unit",
        mk_quantity: "Quantity",
        mk_state: "State",
        mk_district: "District",
        mk_locality: "Locality",
        mk_submit_listing: "List Product",
        mk_cat_veg: "Vegetables",
        mk_cat_fruit: "Fruits",
        mk_cat_grain: "Grains & Pulses",
        mk_cat_seed: "Seeds & Fertilizers",
        mk_cat_machinery: "Machinery",
        unit_kg: "Per kg",
        unit_quintal: "Per quintal",
        unit_piece: "Per piece",
        unit_ton: "Per ton",

        // Gamification
        gami_xp: "Experience",
        gami_take_quiz: "Take Daily Quiz",
        gami_correct: "Correct!",
        gami_incorrect: "Incorrect.",
        gami_got_it: "Awesome, Got It!",
        gami_lvl: "Lvl",
        // Loading Page
        loading_status_init: "Initializing...",
        loading_feature_weather: "Weather",
        loading_feature_scanner: "Leaf Scanner",
        loading_feature_calculator: "Calculator",
        loading_feature_roadmap: "Roadmap",
        // Auth Extras
        forgot_password: "Forgot Password",
        forgot_password_link: "Forgot Password?",
        verify_phone: "Verify Phone Number",
        back_to_login: "Back to Login",
        new_password_label: "New Password",
        confirm_new_password_label: "Confirm New Password",
        enter_phone_placeholder: "Enter phone number",
        enter_password_placeholder: "Enter password",
        enter_name_placeholder: "Enter your name",
        create_password_placeholder: "Create password",
        confirm_password_placeholder: "Confirm password",
        enter_registered_phone: "Enter registered phone number",
        enter_new_password_placeholder: "Enter new password",
        confirm_new_password_placeholder: "Confirm new password",
        terms_footer: "By continuing, you agree to our Terms of Service",
        // Subscription & Payment
        current_plan: "Current Plan",
        subscribe_now: "Subscribe Now!",
        recommended_tag: "RECOMMENDED",
        premium_version: "Premium Version",
        select_payment: "Select Payment Method",
        amount_to_pay: "Amount to pay: ₹49",
        pay_via_upi: "Pay via UPI",
        upi_options: "GPay, PhonePe, Paytm, etc.",
        credit_debit_card: "Credit / Debit Card",
        card_options: "Visa, Mastercard, RuPay",
        netbanking: "Netbanking",
        netbanking_options: "All major Indian banks",
        back_btn: "Back",
        waiting_upi: "Waiting for UPI App...",
        complete_payment_msg: "Please check your phone and complete the payment of ₹49.",
        cancel_request: "Cancel Request",
        payment_successful: "Payment Successful!",
        premium_activated: "Your Premium subscription is now active. All features have been unlocked.",
        continue_dashboard: "Continue to Dashboard",
        per_month: "/month",
        // Marketplace Extras
        digital_agri_portal: "Digital Agri-India Portal",
        welcome_marketplace: "Welcome to the Marketplace",
        select_role_continue: "Please select your role to continue",
        i_am_buyer: "I am a Buyer",
        browse_contact_farmers: "Browse & contact farmers directly",
        i_am_farmer: "I am a Farmer",
        list_manage_produce: "List your produce & manage listings",
        agri_marketplace: "Agri-Marketplace",
        marketplace_hero_desc: "Empowering Indian Farmers with Direct Trade & Premium Market Access",
        publish_listing: "Publish Listing",
        my_active_listings: "My Active Listings",
        listings_appear_here: "Your published listings will appear here",
        location_map_label: "Location (Google Maps Link)",
        paste_map_link: "Paste Map Link or Get GPS",
        whatsapp_number: "WhatsApp Number",
        ten_digit_placeholder: "10-digit number",
        select_state: "Select State",
        select_district: "Select District",
        enter_village_area: "Enter village or area name",
        // Cart & Checkout
        my_cart: "My Cart",
        your_cart_empty: "Your cart is empty",
        add_items_begin: "Add items from the marketplace to begin",
        total_label: "Total",
        proceed_checkout: "Proceed to Checkout",
        secure_checkout: "Secure Checkout",
        order_summary: "Order Summary",
        subtotal: "Subtotal",
        delivery: "Delivery",
        direct_from_farmer: "Direct from Farmer",
        your_details: "Your Details",
        your_full_name: "Your Full Name",
        your_whatsapp: "Your WhatsApp Number",
        delivery_address: "Delivery Address (Optional)",
        village_city_pin: "Village / City / Pincode",
        order_whatsapp_note: "Your order will be sent via WhatsApp to each farmer. They will confirm availability and arrange delivery directly.",
        send_order_whatsapp: "Send Order via WhatsApp",
        // Profile
        farming_statistics: "Farming Statistics",
        leaf_scans_stat: "Leaf Scans",
        weather_checks_stat: "Weather Checks",
        calculations_stat: "Calculations",
        crops_tracked_stat: "Crops Tracked",
        farming_history: "Farming History",
        export_pdf: "Export PDF",
        all_activities: "All Activities",
        scans_filter: "Scans",
        weather_filter: "Weather",
        calculations_filter: "Calculations",
        crops_filter: "Crops",
        no_activities_yet: "No activities yet. Start using BharatFarm to see your farming history!",
        preferences_title: "Preferences",
        preferred_crops: "Preferred Crops",
        none_selected: "None selected",
        not_set: "Not set",
        edit_label: "Edit",
        save_label: "Save",
        cancel_label: "Cancel",
        // Scanner Extras
        scanner_full_desc: "Upload or capture a photo of any plant leaf to detect diseases and get fertilizer recommendations.",
        supports_formats: "Supports: JPG, PNG, WEBP",
        open_camera: "Open Camera",
        take_photo_title: "Take Photo",
        capture_btn: "Capture",
        retake_btn: "Retake",
        use_photo_btn: "Use Photo",
        analysis_result: "Analysis Result",
        plant_status: "Plant Status",
        desc_appear_here: "Description will appear here.",
        // Weather Extras
        enter_village_city: "Enter village or city name",
        refresh_btn: "Refresh",
        offline_note: "You are offline. Cached weather will be shown when available.",
        fetching_weather: "Fetching weather data...",
        safe_farming_title: "SAFE for Farming Activities",
        what_to_do: "What to Do",
        what_not_to_do: "What Not to Do",
        ai_farming_advice: "AI Farming Advice",
        generating_advice: "Generating advice...",
        // Calculator Extras
        cost_only_note: "Only seed and fertilizer costs. Labour, equipment NOT included.",
        search_type_crop: "-- Search or Type a crop --",
        please_valid_crop: "Please enter a valid crop",
        acre_unit: "Acre",
        bigha_unit: "Bigha",
        katha_unit: "Katha",
        unit_conversion_info: "1 Bigha = 20 Katha | 1 Bigha ≈ 0.62 Acre | 1 Acre ≈ 32.26 Katha",
        acres_label: "Acres",
        enter_land_size_ph: "Enter land size",
        calculate_total_cost: "Calculate Total Cost",
        required_seed_qty: "Required Seed Quantity",
        total_seed_cost: "Total Seed Cost",
        required_fert_qty: "Required Fertilizer Quantity",
        total_fert_cost: "Total Fertilizer Cost",
        total_farming_input: "TOTAL FARMING INPUT COST",
        // Roadmap Extras
        farming_activity_roadmap: "Farming Activity Roadmap",
        select_crop_schedule: "Select a crop to view the detailed activity schedule",
        please_select_first: "Please select a crop first.",
        select_a_crop_btn: "Select a Crop",
        start_farming_session: "Start Farming Session",
        end_session: "End Session",
        // Wiki
        ai_knowledge_base: "AI-Powered Knowledge Base",
        crop_health_wiki: "Crop Health Wiki",
        wiki_desc: "Comprehensive knowledge base for plant diseases, pests, and soil health",
        search_diseases_crops: "Search diseases, crops...",
        all_wiki: "All",
        plant_wiki: "Plant",
        pest_wiki: "Pest",
        soil_wiki: "Soil",
        loading_disease_db: "Loading disease database...",
        // Footer
        footer_brand_desc: "Intelligent Smart Farming platform empowering Indian farmers with AI-driven crop insights, disease detection, and direct marketplace access.",
        footer_platform: "Platform",
        footer_home: "Home",
        footer_farmer_app: "Farmer App",
        footer_pricing: "Pricing Plans",
        footer_other_links: "Other Links",
        footer_disclaimer: "Disclaimer",
        footer_faq: "FAQs",
        footer_ai_method: "AI Methodology",
        footer_legal: "Legal",
        footer_terms: "Terms & Conditions",
        footer_privacy: "Privacy Policy",
        footer_data_protection: "Data Protection",
        footer_accessibility: "Accessibility",
        footer_about: "About",
        footer_about_section: "About Section",
        footer_last_updated: "Last updated: 16-03-2026",
        footer_copyright: "© 2026 Bharat Farm. Empowering Indian Agriculture.",
        // Bottom Nav
        nav_home: "Home",
        nav_weather: "Weather",
        nav_market: "Market",
        nav_about: "About",
        nav_crops: "Crops",
        nav_wiki: "Wiki",
        nav_quiz: "Quiz",
        nav_calc: "Calc",
        // About Page
        about_tagline: "Smart Agriculture Platform",
        about_heading: "About BharatFarm",
        about_desc: "BharatFarm is a comprehensive web application designed to empower Indian farmers with modern technology and data-driven insights. Our platform provides intelligent tools for crop planning, disease detection, weather monitoring, and financial planning to help farmers make smarter decisions and increase productivity.",
        key_features_title: "Key Features",
        ai_assistant_title: "AI Farming Assistant",
        ai_assistant_desc: "24/7 smart chatbot for personalized agricultural expert advice",
        smart_market_about: "Smart Marketplace",
        smart_market_about_desc: "Integrated e-commerce portal for seeds, tools, and fertilizers",
        ai_scanner_about: "AI Disease Scanner",
        ai_scanner_about_desc: "Advanced Gemini-powered diagnosis for crop health and diseases",
        weather_monitor_about: "Weather Monitoring",
        weather_monitor_about_desc: "Real-time localized weather data with smart safety alerts",
        cost_calc_about: "Cost Calculator",
        cost_calc_about_desc: "AI-augmented financial planning for crop investment and profit",
        activity_roadmap_about: "Activity Roadmap",
        activity_roadmap_about_desc: "Intelligent day-by-day scheduling for optimized cultivation",
        dev_team: "Development Team",
        team_intro_text: "BharatFarm was developed by a dedicated team of students passionate about leveraging technology to support Indian agriculture:",
        lead_dev: "Lead Developer",
        full_stack_dev: "Full Stack Developer",
        backend_dev: "Backend Developer",
        frontend_dev: "Frontend Developer",
        connect_btn: "Connect",
        our_mission: "Our Mission",
        mission_desc: "To bridge the gap between traditional farming practices and modern technology, making advanced agricultural tools accessible to every farmer in India. We believe that with the right information and tools, farmers can significantly improve their yields, reduce costs, and make more informed decisions.",
        all_rights: "© 2026 BharatFarm - All Rights Reserved",
        made_with_love: "Made with ❤ for Indian Farmers",
        // Schemes Extras
        scheme_matchmaker_title: "Scheme Matchmaker",
        find_govt_schemes_desc: "Find government agricultural schemes you are eligible for",
        land_details_title: "Land Details",
        how_much_land: "How much cultivable land do you own? (in Acres)",
        landless_note: "Enter 0 if you are a landless farmer or sharecropper.",
        location_step_title: "Location",
        crop_info_step_title: "Crop Information",
        primary_crop_q: "What is your primary crop? (Optional)",
        searching_text: "Searching...",
        check_another: "Check Another Profile",
        matched_text: "Matched",
        // Dashboard Extras
        dash_activity_desc: "Smart task scheduling based on precise crop lifecycles and hyper-local data.",
        open_roadmap_cta: "Open Roadmap",
        dash_weather_desc: "Real-time hyper-local weather tracking to protect your yield.",
        view_forecast: "View Forecast",
        dash_wiki_title: "Crop Health Wiki",
        dash_wiki_desc: "AI-powered encyclopedia for plant diseases, pests, and soil health.",
        open_wiki: "Open Wiki",
        // Session Dashboard
        current_session: "Current Farming Session",
        session_crop: "Crop",
        session_started: "Started",
        session_input_cost: "Input Cost",
        session_revenue: "Revenue",
        // Quiz
        loading_question: "Loading question..."
    },
    hi: {
        loading_subtitle: "आपका स्मार्ट फार्मिंग डैशबोर्ड तैयार हो रहा है...",
        login_tagline: "बेहतर फसल योजना और उच्च उत्पादकता के लिए आपका स्मार्ट खेती साथी",
        welcome_back: "वापस स्वागत है", 
        login_subtitle: "अपने फार्मिंग डैशबोर्ड तक पहुंचने के लिए लॉगिन करें",
        my_cart: "मेरी कार्ट",
        cart_empty: "आपकी कार्ट खाली है",
        farming_history: "खेती का इतिहास",
        preferred_crops: "पसंदीदा फसलें",
        footer_platform: "मंच",
        footer_links: "अन्य लिंक",
        footer_legal: "कानूनी",
        footer_about: "बारे में",
        feat_ai_assistant: "एआई कृषि सहायक",
        feat_smart_market: "स्मार्ट मार्केटप्लेस",
        feat_disease_scanner: "एआई रोग स्कैनर",
        feat_weather: "मौसम की निगरानी",
        feat_cost_calc: "लागत कैलकुलेटर",
        feat_activity_roadmap: "गतिविधि रोडमैप",
        select_language: "भाषा चुनें",
        schemes_step1_note: "यदि आप भूमिहीन किसान या बटाईदार हैं तो 0 दर्ज करें।",
        click_upload: "अपलोड करने के लिए क्लिक करें या छवि खींचकर छोड़ें",
        analyzing_leaf: "पत्ती की छवि का विश्लेषण हो रहा है...",
        humidity_label: "नमी",
        wind_speed_label: "हवा की गति",
        visibility_label: "दृश्यता",
        weather_suitable: "मौसम की स्थिति खेती की गतिविधियों के लिए अनुकूल है।",
        prev_page: "पिछला",
        next_page: "अगला",
        climate_req: "जलवायु आवश्यकता",
        generating_insights: "एआई अंतर्दृष्टि उत्पन्न हो रही है...",
        select_land_unit: "भूमि इकाई चुनें",
        revenue_explanation: "अपेक्षित राजस्व देखने के लिए फसल चुनें और भूमि का आकार दर्ज करें।",
        quiz_loading_q: "प्रश्न लोड हो रहा है...",
        login: "लॉगिन", 
        register: "रजिस्टर", 
        phone_number: "फोन नंबर", 
        password: "पासवर्ड",
        full_name: "पूरा नाम", 
        confirm_password: "पासवर्ड की पुष्टि करें", 
        logout: "लॉगआउट",
        dashboard: "डैशबोर्ड", 
        leaf_scanner: "पत्ती स्कैनर", 
        weather: "मौसम", 
        crops: "फसलें",
        calculator: "कैलकुलेटर", 
        roadmap: "रोडमैप", 
        alerts: "अलर्ट", 
        welcome: "स्वागत है",
        dashboard_subtitle: "बेहतर फसल योजना के लिए आपका स्मार्ट खेती साथी",
        weather_status: "मौसम", 
        scan_now: "स्कैन करें", 
        detect_disease: "रोग पता करें",
        next_activity: "अगली गतिविधि", 
        view_roadmap: "रोडमैप देखें", 
        input_cost: "इनपुट लागत",
        calculate: "गणना करें", 
        revenue: "राजस्व", 
        view_details: "विवरण",
        quick_tips: "आज के लिए त्वरित सुझाव", 
        get_started: "शुरू करें", 
        scan_leaf: "पत्ती स्कैन करें",
        check_weather: "मौसम जांचें", 
        select_crop: "फसल चुनें", 
        calculate_costs: "लागत गणना करें",
        leaf_disease_scanner: "पत्ती रोग स्कैनर",
        scanner_desc: "रोग का पता लगाने और उर्वरक सिफारिशें प्राप्त करने के लिए किसी भी पौधे की पत्ती की फोटो अपलोड करें।",
        upload_leaf: "पत्ती की छवि अपलोड करें", 
        click_or_drag: "अपलोड करने के लिए क्लिक करें",
        take_photo: "फोटो लें", 
        browse_files: "फाइलें ब्राउज़ करें", 
        analyze_leaf: "पत्ती का विश्लेषण करें",
        analyzing: "पत्ती का विश्लेषण हो रहा है...", 
        enter_location: "अपना स्थान दर्ज करें",
        get_weather: "मौसम प्राप्त करें", 
        rain_probability: "बारिश", 
        humidity: "आर्द्रता", 
        wind: "हवा",
        visibility: "दृश्यता", 
        safe_farming: "खेती के लिए सुरक्षित",
        safe_msg: "मौसम की स्थिति खेती गतिविधियों के लिए उपयुक्त है।",
        unsafe_farming: "खेती के लिए असुरक्षित", 
        unsafe_msg: "बारिश की उच्च संभावना। उर्वरक न डालें।",
        crop_desc: "विस्तृत खेती सिफारिशें देखने के लिए फसल चुनें।",
        crop_info: "फसल जानकारी", 
        duration: "अवधि", 
        watering: "सिंचाई", 
        fertilizers: "उर्वरक",
        schedule: "अनुसूची", 
        cost_calculator: "बीज और उर्वरक लागत कैलकुलेटर",
        cost_note: "केवल बीज और उर्वरक लागत। 2024 भारत बाजार दरें।",
        land_unit: "भूमि इकाई चुनें", 
        land_size: "भूमि का आकार", 
        cost_breakdown: "लागत विवरण",
        seed_qty: "बीज मात्रा", 
        seed_cost: "बीज लागत", 
        fert_qty: "उर्वरक मात्रा",
        fert_cost: "उर्वरक लागत", 
        total_cost: "कुल इनपुट लागत",
        revenue_prediction: "राजस्व भविष्यवाणी", 
        expected_revenue: "अपेक्षित राजस्व",
        revenue_note: "अपेक्षित राजस्व देखने के लिए फसल और भूमि आकार चुनें।",
        expected_yield: "अपेक्षित उपज", 
        market_price: "बाजार मूल्य", 
        profit_margin: "लाभ मार्जिन",
        crop_roadmap: "फसल गतिविधि रोडमैप", 
        select_crop_first: "अनुसूची देखने के लिए फसल चुनें",
        select_crop_roadmap: "रोडमैप बनाने के लिए पहले फसल चुनें।",
        notifications: "सूचनाएं और अलर्ट",
        tip_morning: "सुबह: सिंचाई का सबसे अच्छा समय - वाष्पीकरण कम होता है।",
        tip_afternoon: "दोपहर: गर्म घंटों में कीटों की जांच करें।",
        tip_evening: "शाम: बेहतर अवशोषण के लिए उर्वरक डालें।",
        healthy_plant: "स्वस्थ पौधा", 
        disease_detected: "रोग पाया गया",
        recommended_fertilizers: "अनुशंसित उर्वरक", 
        treatment_tips: "उपचार सुझाव",
        // Crop section
        crop_search_placeholder: "फसल खोजें (जैसे, टमाटर, चावल...)",
        crop_search_desc: "किसी भी फसल की विस्तृत खेती सिफारिशें देखने के लिए खोजें।",
        cat_all: "सभी",
        cat_cereal: "अनाज",
        cat_vegetable: "सब्ज़ी",
        cat_fruit: "फल",
        cat_oilseed: "तिलहन",
        searching_crops: "फसल डेटाबेस खोज रहे हैं...",
        no_crops_found: "आपकी खोज से मेल खाती कोई फसल नहीं मिली। कोई अन्य नाम या श्रेणी आज़माएं।",
        previous: "पिछला",
        next: "अगला",
        scientific_name: "वैज्ञानिक नाम",
        climate_requirement: "जलवायु आवश्यकता",
        soil_type: "मिट्टी का प्रकार",
        total_duration: "कुल अवधि",
        water_requirement: "पानी की आवश्यकता",
        harvesting_period: "कटाई की अवधि",
        ai_insights: "एआई उगाने की जानकारी",
        view_roadmap_btn: "रोडमैप देखें",
        calculate_costs_btn: "लागत गणना करें",
        crop_info_label: "फसल जानकारी",
        cropNames: {
            tomato: "टमाटर", potato: "आलू", onion: "प्याज", carrot: "गाजर",
            cabbage: "पत्तागोभी", spinach: "पालक", brinjal: "बैंगन",
            cauliflower: "फूलगोभी", okra: "भिंडी", capsicum: "शिमला मिर्च",
            mango: "आम", banana: "केला", apple: "सेब", papaya: "पपीता",
            guava: "अमरूद", orange: "संतरा", grapes: "अंगूर", pomegranate: "अनार",
            watermelon: "तरबूज", pineapple: "अनानास",
            rice: "चावल", wheat: "गेहूं", maize: "मक्का", barley: "जौ", oats: "जई",
            mustard: "सरसों", soybean: "सोयाबीन", sunflower: "सूरजमुखी", groundnut: "मूंगफली"
        },
        categoryNames: {
            vegetable: "सब्ज़ी", fruit: "फल", cereal: "अनाज", oilseed: "तिलहन"
        },
        // Schemes
        schemes_title: "सरकारी योजना मिलान",
        schemes_subtitle: "पता करें कि आप किन सरकारी योजनाओं और सब्सिडी के पात्र हैं",
        schemes_step1_title: "खेत का आकार",
        schemes_step1_label: "आप कितनी भूमि पर खेती करते हैं?",
        schemes_step1_placeholder: "एकड़ में जमीन का आकार दर्ज करें",
        schemes_step2_title: "आपका राज्य",
        schemes_step2_label: "अपना राज्य चुनें",
        schemes_step2_placeholder: "-- राज्य चुनें --",
        schemes_step3_title: "मुख्य फसल",
        schemes_step3_label: "आपकी मुख्य फसल क्या है?",
        schemes_step3_placeholder: "जैसे, चावल, गेहूं, टमाटर...",
        schemes_prev: "पिछला",
        schemes_next: "अगला",
        schemes_find: "योजनाएं खोजें",
        schemes_finding: "योजनाएं खोजी जा रही हैं...",
        schemes_back: "फिर से खोजें",
        schemes_eligible: "पात्र योजनाएं",
        schemes_matched: "योजनाएं मिलीं",
        schemes_empty_title: "कोई योजना नहीं मिली",
        schemes_empty_msg: "आपकी प्रोफाइल से मेल खाती कोई योजना नहीं मिली। बाद में दोबारा देखें या जानकारी बदलें।",
        schemes_try_again: "फिर से कोशिश करें",
        schemes_eligibility: "पात्रता",
        schemes_benefits: "लाभ / मुनाफा",
        schemes_apply: "अभी आवेदन करें",
        schemes_any_size: "कोई भी आकार",
        schemes_all_states: "सभी राज्य",
        schemes_all_crops: "सभी फसलें",
        schemes_central: "केंद्रीय",
        schemes_state: "राज्य",
        schemes_centralstate: "केंद्र/राज्य",
        marketplace_title: "बाज़ार",
        marketplace_label: "खरीदें और बेचें",
        marketplace_status: "खुला है",
        schemes_title_short: "सरकारी योजनाएं",
        schemes_check_eligibility: "पात्रता जांचें",
        schemes_matchmaker: "मैचमेकर",
        premium_marketplace: "एआई-संचालित बाज़ार",
        premium_trade: "सीधे खरीदार से व्यापार",
        premium_commission: "जीरो कमीशन बिक्री",
        premium_leaf_scanner: "पत्ती रोग स्कैनर",
        premium_roadmap: "खेती गतिविधि रोडमैप",
        premium_weather: "उन्नत मौसम अलर्ट",
        premium_revenue: "राजस्व भविष्यवाणी",
        premium_support: "प्राथमिकता सहायता",
        premium_ad_free: "विज्ञापन-मुक्त अनुभव",
        premium_plan_title: "अपनी खेती योजना चुनें",
        premium_plan_subtitle: "अपनी उपज बढ़ाने के लिए उन्नत टूल्स अनलॉक करें",
        premium_free_month: "सभी नए उपयोगकर्ताओं के लिए पहला महीना मुफ़्त है!",
        free_version: "मुफ्त संस्करण",
        free_dashboard: "मूल डैशबोर्ड",
        free_weather: "मौसम ओपडेट",
        free_calculator: "लागत कैलकुलेटर",
        free_marketplace: "बाज़ार ब्राउज़ करें",
        free_roadmap: "विस्तृत गतिविधि रोडमैप",
        free_support: "विशेषज्ञ सहायता",
        schemes_loading_msg_1: "हमारे अन्नदाता की मदद कर रहे हैं... आपकी समृद्धि के लिए बेहतरीन सरकारी योजनाएं खोज रहे हैं।",
        schemes_loading_msg_2: "सूचना के बीज बो रहे हैं... आपके खेत के लिए नवीनतम अपडेट प्राप्त कर रहे हैं।",
        // Redesigned Dashboard HI Keys
        hero_title: "आपका एआई साथ",
        hero_accent: "स्मार्ट खेती के लिए",
        hero_sub: "स्वागत है, <strong><span id=\"welcomeName\">किसान</span></strong>! वास्तविक समय की जानकारी, आवाज-आधारित सहायता और सीधे बाजार पहुंच के साथ भारतीय कृषि को सशक्त बनाना।",
        hero_get_started: "शुरू करें",
        hero_explore: "इकोसिस्टम देखें",
        float_weather_label: "मौसम अलर्ट",
        float_activity_label: "अगली गतिविधि",
        float_activity_value: "फसल चुनें",
        float_roadmap_status: "रोडमैप देखें",
        ecosystem_tag: "इकोसिस्टम",
        ecosystem_title: "भविष्य की खेती",
        kb_title: "कृषिबॉट: वॉयस फर्स्ट एआई",
        kb_desc: "अपने खेत से बात करें। सिंचाई, कीट नियंत्रण और बाजार के रुझानों पर अपनी स्थानीय भाषा में सलाह लें।",
        kb_cta: "अभी बात करें",
        ls_title: "पत्ती स्कैनर",
        ls_desc: "एक ही फोटो से त्वरित जेमिनाई-संचालित फसल रोग निदान।",
        ls_cta: "स्वैन शुरू करें",
        sm_title: "स्मार्ट मार्केट",
        sm_desc: "सीधे शहरी समूहों को बेचें। बिचौलियों को खत्म करें।",
        sm_cta: "मार्केट खोलें",
        ha_title: "हाइपरलोकल एनालिटिक्स",
        ha_desc: "आपके विशिष्ट स्थान के लिए मिट्टी की नमी, पोषक तत्व स्तर और सटीक मौसम पूर्वानुमान।",
        ha_input_label: "इनपुट लागत",
        ha_revenue_label: "राजस्व",
        gs_title: "सरकारी योजनाएं",
        gs_desc: "पीएम-किसान, पीएमएफबीवाई और राज्य-विशिष्ट सब्सिडी के लिए पात्रता जांचें।",
        gs_cta: "मैचमेकर",
        impact_title: "मिट्टी से आत्मा तक।",
        impact_desc: "हम सिर्फ डेटा प्रदान नहीं करते हैं; हम मेहनती किसान और जागरूक उपभोक्ता के बीच एक सेतु प्रदान करते हैं।",
        impact_stat1_title: "स्थिरता पहले",
        impact_stat1_desc: "एआई सटीकता के माध्यम से उर्वरक कचरे को 30% कम करना",
        impact_stat2_title: "उचित मूल्य",
        impact_stat2_desc: "सीधे वितरण सुनिश्चित करता है कि किसानों को खुदरा मूल्य का 85% मिले",
        // Marketplace & Header HI
        header_premium: "प्रीमियम",
        header_logout: "लॉगआउट",
        mk_browse: "बाज़ार देखें",
        mk_sell: "उपज बेचें",
        mk_role_buyer: "खरीददार",
        mk_role_farmer: "किसान",
        mk_switch_role: "भूमिका बदलें",
        mk_search_placeholder: "फसलें, किसान या क्षेत्र खोजें...",
        mk_add_listing: "नई लिस्टिंग जोड़ें",
        mk_product_name: "उत्पाद का नाम",
        mk_crop_placeholder: "फसल चुनें या टाइप करें...",
        mk_category: "श्रेणी",
        mk_price: "कीमत (रुपये)",
        mk_unit: "इकाई",
        mk_quantity: "मात्रा",
        mk_state: "राज्य",
        mk_district: "जिला",
        mk_locality: "इलाका",
        mk_submit_listing: "उत्पाद सूचीबद्ध करें",
        mk_cat_veg: "सब्जियां",
        mk_cat_fruit: "फल",
        mk_cat_grain: "अनाज और दालें",
        mk_cat_seed: "बीज और उर्वरक",
        mk_cat_machinery: "मशीनरी",
        unit_kg: "प्रति किलो",
        unit_quintal: "प्रति क्विंटल",
        unit_piece: "प्रति नग",
        unit_ton: "प्रति टन",
        // Gamification
        gami_xp: "अनुभव",
        gami_take_quiz: "दैनिक प्रश्नोत्तरी लें",
        gami_correct: "सही!",
        gami_incorrect: "गलत।",
        gami_got_it: "बहुत बढ़िया, समझ गया!",
        gami_lvl: "स्तर",
        // Loading Page
        loading_status_init: "प्रारंभ हो रहा है...",
        loading_feature_weather: "मौसम",
        loading_feature_scanner: "पत्ती स्कैनर",
        loading_feature_calculator: "कैलकुलेटर",
        loading_feature_roadmap: "रोडमैप",
        // Auth Extras
        forgot_password: "पासवर्ड भूल गए",
        forgot_password_link: "पासवर्ड भूल गए?",
        verify_phone: "फ़ोन नंबर सत्यापित करें",
        back_to_login: "लॉगिन पर वापस जाएं",
        new_password_label: "नया पासवर्ड",
        confirm_new_password_label: "नए पासवर्ड की पुष्टि करें",
        enter_phone_placeholder: "फ़ोन नंबर दर्ज करें",
        enter_password_placeholder: "पासवर्ड दर्ज करें",
        enter_name_placeholder: "अपना नाम दर्ज करें",
        create_password_placeholder: "पासवर्ड बनाएं",
        confirm_password_placeholder: "पासवर्ड की पुष्टि करें",
        enter_registered_phone: "पंजीकृत फ़ोन नंबर दर्ज करें",
        enter_new_password_placeholder: "नया पासवर्ड दर्ज करें",
        confirm_new_password_placeholder: "नए पासवर्ड की पुष्टि करें",
        terms_footer: "जारी रखकर, आप हमारी सेवा की शर्तों से सहमत हैं",
        // Subscription & Payment
        current_plan: "वर्तमान योजना",
        subscribe_now: "अभी सदस्यता लें!",
        recommended_tag: "अनुशंसित",
        premium_version: "प्रीमियम संस्करण",
        select_payment: "भुगतान विधि चुनें",
        amount_to_pay: "भुगतान की जाने वाली राशि: ₹49",
        pay_via_upi: "UPI के माध्यम से भुगतान करें",
        upi_options: "GPay, PhonePe, Paytm, आदि",
        credit_debit_card: "क्रेडिट / डेबिट कार्ड",
        card_options: "Visa, Mastercard, RuPay",
        netbanking: "नेटबैंकिंग",
        netbanking_options: "सभी प्रमुख भारतीय बैंक",
        back_btn: "वापस",
        waiting_upi: "UPI ऐप की प्रतीक्षा कर रहा है...",
        complete_payment_msg: "कृपया अपना फ़ोन जांचें और ₹49 का भुगतान पूरा करें।",
        cancel_request: "अनुरोध रद्द करें",
        payment_successful: "भुगतान सफल!",
        premium_activated: "आपकी प्रीमियम सदस्यता अब सक्रिय है। सभी सुविधाएँ अनलॉक कर दी गई हैं।",
        continue_dashboard: "डैशबोर्ड पर जारी रखें",
        per_month: "/महीना"
    },
    bn: {
        loading_subtitle: "আপনার স্মার্ট ফার্মিং ড্যাশবোর্ড প্রস্তুত হচ্ছে...",
        login_tagline: "উন্নত ফসল পরিকল্পনা এবং উচ্চ উৎপাদনশীলতার জন্য আপনার স্মার্ট কৃষি সহায়ক",
        welcome_back: "স্বাগতম", 
        login_subtitle: "আপনার ফার্মিং ড্যাশবোর্ড অ্যাক্সেস করতে লগইন করুন",
        my_cart: "আমার কার্ট",
        cart_empty: "আপনার কার্ট খালি",
        farming_history: "কৃষি ইতিহাস",
        preferred_crops: "পছন্দের ফসল",
        footer_platform: "প্ল্যাটফর্ম",
        footer_links: "অন্যান্য লিঙ্ক",
        footer_legal: "আইনি",
        footer_about: "সম্পর্কে",
        feat_ai_assistant: "এআই কৃষি সহকারী",
        feat_smart_market: "স্মার্ট মার্কেটপ্লেস",
        feat_disease_scanner: "এআই রোগ স্ক্যানার",
        feat_weather: "আবহাওয়া পর্যবেক্ষণ",
        feat_cost_calc: "খরচ ক্যালকুলেটর",
        feat_activity_roadmap: "কার্যকলাপের রোডম্যাপ",
        select_language: "ভাষা নির্বাচন করুন",
        schemes_step1_note: "আপনি যদি ভূমিহীন কৃষক বা ভাগচাষী হন তাহলে 0 লিখুন।",
        click_upload: "আপলোড করতে ক্লিক করুন বা ছবি টেনে আনুন",
        analyzing_leaf: "পাতার ছবি বিশ্লেষণ করা হচ্ছে...",
        humidity_label: "আর্দ্রতা",
        wind_speed_label: "বায়ুর গতি",
        visibility_label: "দৃশ্যমানতা",
        weather_suitable: "আবহাওয়া পরিস্থিতি কৃষি কাজের জন্য উপযুক্ত।",
        prev_page: "পূর্ববর্তী",
        next_page: "পরবর্তী",
        climate_req: "জলবায়ু প্রয়োজনীয়তা",
        generating_insights: "এআই অন্তর্দৃষ্টি তৈরি হচ্ছে...",
        select_land_unit: "জমির একক নির্বাচন করুন",
        revenue_explanation: "প্রত্যাশিত আয় দেখতে ফসল নির্বাচন করুন এবং জমির আকার লিখুন।",
        quiz_loading_q: "প্রশ্ন লোড হচ্ছে...",
        login: "লগইন", 
        register: "নিবন্ধন", 
        phone_number: "ফোন নম্বর", 
        password: "পাসওয়ার্ড",
        full_name: "পুরো নাম", 
        confirm_password: "পাসওয়ার্ড নিশ্চিত করুন", 
        logout: "লগআউট",
        dashboard: "ড্যাশবোর্ড", 
        leaf_scanner: "পাতা স্ক্যানার", 
        weather: "আবহাওয়া", 
        crops: "ফসল",
        calculator: "ক্যালকুলেটর", 
        roadmap: "রোডম্যাপ", 
        alerts: "সতর্কতা", 
        welcome: "স্বাগতম",
        dashboard_subtitle: "উন্নত ফসল পরিকল্পনার জন্য আপনার স্মার্ট কৃষি সহায়ক",
        weather_status: "আবহাওয়া", 
        scan_now: "স্ক্যান করুন", 
        detect_disease: "রোগ সনাক্ত করুন",
        next_activity: "পরবর্তী কাজ", 
        view_roadmap: "রোডম্যাপ দেখুন", 
        input_cost: "ইনপুট খরচ",
        calculate: "গণনা করুন", 
        revenue: "আয়", 
        view_details: "বিবরণ",
        quick_tips: "আজকের দ্রুত টিপস", 
        get_started: "শুরু করুন", 
        scan_leaf: "পাতা স্ক্যান করুন",
        check_weather: "আবহাওয়া দেখুন", 
        select_crop: "ফসল নির্বাচন করুন", 
        calculate_costs: "খরচ গণনা করুন",
        leaf_disease_scanner: "পাতার রোগ স্ক্যানার",
        scanner_desc: "রোগ সনাক্ত করতে এবং সার সুপারিশ পেতে যেকোনো গাছের পাতার ছবি আপলোড করুন।",
        upload_leaf: "পাতার ছবি আপলোড করুন", 
        click_or_drag: "আপলোড করতে ক্লিক করুন",
        take_photo: "ছবি তুলুন", 
        browse_files: "ফাইল ব্রাউজ করুন", 
        analyze_leaf: "পাতা বিশ্লেষণ করুন",
        analyzing: "পাতা বিশ্লেষণ হচ্ছে...", 
        enter_location: "আপনার অবস্থান দিন",
        get_weather: "আবহাওয়া দেখুন", 
        rain_probability: "বৃষ্টি", 
        humidity: "আর্দ্রতা", 
        wind: "বাতাস",
        visibility: "দৃশ্যমানতা", 
        safe_farming: "কৃষির জন্য নিরাপদ",
        safe_msg: "আবহাওয়া কৃষি কাজের জন্য উপযুক্ত।",
        unsafe_farming: "কৃষির জন্য অনিরাপদ", 
        unsafe_msg: "বৃষ্টির উচ্চ সম্ভাবনা। সার দেবেন না।",
        crop_desc: "বিস্তারিত কৃষি সুপারিশ দেখতে ফসল নির্বাচন করুন।",
        crop_info: "ফসল তথ্য", 
        duration: "সময়কাল", 
        watering: "সেচ", 
        fertilizers: "সার",
        schedule: "সময়সূচী", 
        cost_calculator: "বীজ ও সার খরচ ক্যালকুলেটর",
        cost_note: "শুধু বীজ ও সার খরচ। ২০২৪ ভারত বাজার দর।",
        land_unit: "জমির একক নির্বাচন করুন", 
        land_size: "জমির আকার", 
        cost_breakdown: "খরচ বিবরণ",
        seed_qty: "বীজ পরিমাণ", 
        seed_cost: "বীজ খরচ", 
        fert_qty: "সার পরিমাণ",
        fert_cost: "সার খরচ", 
        total_cost: "মোট ইনপুট খরচ",
        revenue_prediction: "আয় পূর্বাভাস", 
        expected_revenue: "প্রত্যাশিত আয়",
        revenue_note: "প্রত্যাশিত আয় দেখতে ফসল এবং জমির আকার নির্বাচন করুন।",
        expected_yield: "প্রত্যাশিত ফলন", 
        market_price: "বাজার মূল্য", 
        profit_margin: "লাভের হার",
        crop_roadmap: "ফসল কার্যক্রম রোডম্যাপ", 
        select_crop_first: "সময়সূচী দেখতে ফসল নির্বাচন করুন",
        select_crop_roadmap: "রোডম্যাপ তৈরি করতে প্রথমে ফসল নির্বাচন করুন।",
        notifications: "বিজ্ঞপ্তি ও সতর্কতা",
        tip_morning: "সকাল: সেচের সেরা সময় - বাষ্পীভবন কম হয়।",
        tip_afternoon: "দুপুর: গরম সময়ে পোকামাকড় পরীক্ষা করুন।",
        tip_evening: "সন্ধ্যা: ভালো শোষণের জন্য সার দিন।",
        healthy_plant: "সুস্থ গাছ", 
        disease_detected: "রোগ সনাক্ত হয়েছে",
        recommended_fertilizers: "প্রস্তাবিত সার", 
        treatment_tips: "চিকিৎসা টিপস",
        // Crop section
        crop_search_placeholder: "ফসল খুঁজুন (যেমন, টমেটো, ধান...)",
        crop_search_desc: "যেকোনো ফসলের বিস্তারিত কৃষি সুপারিশ দেখতে অনুসন্ধান করুন।",
        cat_all: "সব",
        cat_cereal: "শস্য",
        cat_vegetable: "সবজি",
        cat_fruit: "ফল",
        cat_oilseed: "তৈলবীজ",
        searching_crops: "ফসল ডাটাবেস খোঁজা হচ্ছে...",
        no_crops_found: "আপনার অনুসন্ধানের সাথে কোনো ফসল পাওয়া যায়নি। অন্য নাম বা শ্রেণী চেষ্টা করুন।",
        previous: "পূর্ববর্তী",
        next: "পরবর্তী",
        scientific_name: "বৈজ্ঞানিক নাম",
        climate_requirement: "জলবায়ু প্রয়োজনীয়তা",
        soil_type: "মাটির ধরন",
        total_duration: "মোট সময়কাল",
        water_requirement: "পানির প্রয়োজনীয়তা",
        harvesting_period: "ফসল কাটার সময়কাল",
        ai_insights: "এআই চাষের অন্তর্দৃষ্টি",
        view_roadmap_btn: "রোডম্যাপ দেখুন",
        calculate_costs_btn: "খরচ হিসাব করুন",
        crop_info_label: "ফসল তথ্য",
        cropNames: {
            tomato: "টমেটো", potato: "আলু", onion: "পেঁয়াজ", carrot: "গাজর",
            cabbage: "বাঁধাকপি", spinach: "পালং শাক", brinjal: "বেগুন",
            cauliflower: "ফুলকপি", okra: "ঢেঁড়স", capsicum: "ক্যাপসিকাম",
            mango: "আম", banana: "কলা", apple: "আপেল", papaya: "পেঁপে",
            guava: "পেয়ারা", orange: "কমলা", grapes: "আঙুর", pomegranate: "ডালিম",
            watermelon: "তরমুজ", pineapple: "আনারস",
            rice: "ধান", wheat: "গম", maize: "ভুট্টা", barley: "যব", oats: "ওটস",
            mustard: "সরিষা", soybean: "সয়াবিন", sunflower: "সূর্যমুখী", groundnut: "চিনাবাদাম"
        },
        categoryNames: {
            vegetable: "সবজি", fruit: "ফল", cereal: "শস্য", oilseed: "তৈলবীজ"
        },
        // Schemes
        schemes_title: "সরকারি প্রকল্প খোঁজক",
        schemes_subtitle: "আপনি কোন সরকারি প্রকল্প ও ভর্তুকির যোগ্য তা খুঁজে বের করুন",
        schemes_step1_title: "জমির আকার",
        schemes_step1_label: "আপনি কত জমিতে চাষ করেন?",
        schemes_step1_placeholder: "একরে জমির আকার দিন",
        schemes_step2_title: "আপনার রাজ্য",
        schemes_step2_label: "আপনার রাজ্য নির্বাচন করুন",
        schemes_step2_placeholder: "-- রাজ্য নির্বাচন করুন --",
        schemes_step3_title: "প্রধান ফসল",
        schemes_step3_label: "আপনার প্রধান ফসল কী?",
        schemes_step3_placeholder: "যেমন ধান, গম, টমেটো...",
        schemes_prev: "পূর্ববর্তী",
        schemes_next: "পরবর্তী",
        schemes_find: "আমার প্রকল্প খুঁজুন",
        schemes_finding: "প্রকল্প খোঁজা হচ্ছে...",
        schemes_back: "আবার খুঁজুন",
        schemes_eligible: "যোগ্য প্রকল্পসমূহ",
        schemes_matched: "প্রকল্প পাওয়া গেছে",
        schemes_empty_title: "কোনো প্রকল্প পাওয়া যায়নি",
        schemes_empty_msg: "আপনার প্রোফাইলের সাথে মেলে এমন কোনো প্রকল্প পাওয়া যায়নি। পরে আবার চেষ্টা করুন।",
        schemes_try_again: "আবার চেষ্টা করুন",
        schemes_eligibility: "যোগ্যতা",
        schemes_benefits: "সুবিধা / লাভ",
        schemes_apply: "এখনই আবেদন করুন",
        schemes_any_size: "যেকোনো আকার",
        schemes_all_states: "সব রাজ্য",
        schemes_all_crops: "সব ফসল",
        schemes_central: "কেন্দ্রীয়",
        schemes_state: "রাজ্য",
        schemes_centralstate: "কেন্দ্র/রাজ্য",
        marketplace_title: "মার্কেটপ্লেস",
        marketplace_label: "কেনা ও বেচা",
        marketplace_status: "খোলা আছে",
        schemes_title_short: "সরকারি প্রকল্প",
        schemes_check_eligibility: "যোগ্যতা যাচাই করুন",
        schemes_matchmaker: "ম্যাচমেকার",
        premium_marketplace: "এআই-চালিত মার্কেটপ্লেস",
        premium_trade: "সরাসরি ক্রেতার সাথে বাণিজ্য",
        premium_commission: "শূন্য কমিশন বিক্রয়",
        premium_leaf_scanner: "পাতার রোগ স্ক্যানার",
        premium_roadmap: "কৃষি কার্যক্রম রোডম্যাপ",
        premium_weather: "উন্নত আবহাওয়া সতর্কতা",
        premium_revenue: "আয় পূর্বাভাস",
        premium_support: "অগ্রাধিকার সহায়তা",
        premium_ad_free: "বিজ্ঞাপন-মুক্ত অভিজ্ঞতা",
        premium_plan_title: "আপনার কৃষি পরিকল্পনা নির্বাচন করুন",
        premium_plan_subtitle: "আপনার ফলন বাড়াতে উন্নত সরঞ্জাম আনলক করুন",
        premium_free_month: "নতুন ব্যবহারকারীদের জন্য প্রথম মাস সম্পূর্ণ বিনামূল্যে!",
        free_version: "ফ্রি ভার্সন",
        free_dashboard: "বেসিক ড্যাশবোর্ড",
        free_weather: "আবহাওয়া আপডেট",
        free_calculator: "খরচ ক্যালকুলেটর",
        free_marketplace: "মার্কেটপ্লেস ব্রাউজ",
        free_roadmap: "বিস্তারিত টিপস ও কার্যক্রম",
        free_support: "বিশেষজ্ঞ সহায়তা",
        schemes_loading_msg_1: "মাটির সেবায় আমরা পাশে আছি... আপনার জন্য সেরা সরকারি যোজনাগুলি খোঁজা হচ্ছে।",
        schemes_loading_msg_2: "আপনার খামারের উন্নতির লক্ষে সঠিক তথ্যের সন্ধান চলছে... একটু অপেক্ষা করুন।",
        // Redesigned Dashboard BN Keys
        hero_title: "আপনার স্মার্ট চাষের",
        hero_accent: "এআই সঙ্গী",
        hero_sub: "স্বাগতম, <strong><span id=\"welcomeName\">কৃষক</span></strong>! রিয়েল-টাইম ইন্টেলিজেন্স, ভয়েস-ফার্স্ট সহায়তা এবং সরাসরি বাজারে প্রবেশের মাধ্যমে ভারতীয় কৃষিকে শক্তিশালী করছে।",
        hero_get_started: "শুরু করুন",
        hero_explore: "ইকোসিস্টেম দেখুন",
        float_weather_label: "আবহাওয়ার সতর্কবার্তা",
        float_activity_label: "পরবর্তী কাজ",
        float_activity_value: "ফসল নির্বাচন করুন",
        float_roadmap_status: "রোডম্যাপ দেখুন",
        ecosystem_tag: "ইকোসিস্টেম",
        ecosystem_title: "ভবিষ্যতের চাষাবাদ",
        kb_title: "কৃষিবট: ভয়েস ফার্স্ট এআই",
        kb_desc: "আপনার খামারের সাথে কথা বলুন। সেচ, কীটপতঙ্গ নিয়ন্ত্রণ এবং বাজারের প্রবণতা সম্পর্কে আপনার স্থানীয় ভাষায় পরামর্শ নিন।",
        kb_cta: "এখনই কথা বলুন",
        ls_title: "পাতা স্ক্যানার",
        ls_desc: "একটি ছবি থেকেই দ্রুত জেমিনাই-চালিত ফসলের রোগ নির্ণয়।",
        ls_cta: "স্ক্যান শুরু করুন",
        sm_title: "স্মার্ট মার্কেট",
        sm_desc: "সরাসরি শহুরে গ্রাহকদের কাছে বিক্রি করুন। মধ্যস্বত্বভোগী সরান।",
        sm_cta: "মার্কেট খুলুন",
        ha_title: "হাইপারলোকাল অ্যানালিটিক্স",
        ha_desc: "আপনার অবস্থানের জন্য মাটির আর্দ্রতা, পুষ্টির মাত্রা এবং সঠিক আবহাওয়ার পূর্বাভাস।",
        ha_input_label: "ইনপুট খরচ",
        ha_revenue_label: "আয়",
        gs_title: "সরকারি প্রকল্প",
        gs_desc: "পিএম-কিষাণ, পিএমএফবিওয়াই এবং রাজ্য-নির্দিষ্ট ভর্তুকির যোগ্যতা যাচাই করুন।",
        gs_cta: "ম্যাচমেকার",
        impact_title: "মাটি থেকে মন পর্যন্ত।",
        impact_desc: "আমরা শুধু তথ্য দিই না; আমরা পরিশ্রমী কৃষক এবং সচেতন ভোক্তার মধ্যে একটি সেতু তৈরি করি।",
        impact_stat1_title: "স্থায়ীত্ব সবার আগে",
        impact_stat1_desc: "এআই এর মাধ্যমে সারের অপচয় ৩০% কমানো",
        impact_stat2_title: "ন্যায্য মূল্য",
        impact_stat2_desc: "সরাসরি বিক্রয় নিশ্চিত করে যে কৃষকরা খুচরা মূল্যের ৮৫% পান",
        // Marketplace & Header BN
        header_premium: "প্রিমিয়াম",
        header_logout: "লগআউট",
        mk_browse: "মার্কেটপ্লেস দেখুন",
        mk_sell: "ফসল বিক্রি করুন",
        mk_role_buyer: "ক্রেতা",
        mk_role_farmer: "কৃষক",
        mk_switch_role: "ভূমিকা পরিবর্তন",
        mk_search_placeholder: "ফসল, কৃষক বা অঞ্চল খুঁজুন...",
        mk_add_listing: "নতুন তালিকা যোগ করুন",
        mk_product_name: "পণ্যের নাম",
        mk_crop_placeholder: "ফসল টাইপ বা নির্বাচন করুন...",
        mk_category: "বিভাগ",
        mk_price: "মূল্য (টাকা)",
        mk_unit: "একক",
        mk_quantity: "পরিমাণ",
        mk_state: "রাজ্য",
        mk_district: "জেলা",
        mk_locality: "এলাকা",
        mk_submit_listing: "পণ্য তালিকাভুক্ত করুন",
        mk_cat_veg: "শাকসবজি",
        mk_cat_fruit: "ফলমূল",
        mk_cat_grain: "শস্য ও ডাল",
        mk_cat_seed: "বীজ ও সার",
        mk_cat_machinery: "যন্ত্রপাতি",
        unit_kg: "প্রতি কেজি",
        unit_quintal: "প্রতি কুইন্টাল",
        unit_piece: "প্রতি পিস",
        unit_ton: "প্রতি টন",

        // Gamification
        gami_xp: "অভিজ্ঞতা",
        gami_take_quiz: "দৈনিক কুইজ খেলুন",
        gami_correct: "সঠিক!",
        gami_incorrect: "ভুল।",
        gami_got_it: "চমৎকার, বুঝতে পেরেছি!",
        gami_lvl: "স্তর",
        // Loading Page
        loading_status_init: "শুরু হচ্ছে...",
        loading_feature_weather: "আবহাওয়া",
        loading_feature_scanner: "পাতা স্ক্যানার",
        loading_feature_calculator: "ক্যালকুলেটর",
        loading_feature_roadmap: "রোডম্যাপ",
        // Auth Extras
        forgot_password: "পাসওয়ার্ড ভুলে গেছেন",
        forgot_password_link: "পাসওয়ার্ড ভুলে গেছেন?",
        verify_phone: "ফোন নম্বর যাচাই করুন",
        back_to_login: "লগইনে ফিরে যান",
        new_password_label: "নতুন পাসওয়ার্ড",
        confirm_new_password_label: "নতুন পাসওয়ার্ড নিশ্চিত করুন",
        enter_phone_placeholder: "ফোন নম্বর লিখুন",
        enter_password_placeholder: "পাসওয়ার্ড লিখুন",
        enter_name_placeholder: "আপনার নাম লিখুন",
        create_password_placeholder: "পাসওয়ার্ড তৈরি করুন",
        confirm_password_placeholder: "পাসওয়ার্ড নিশ্চিত করুন",
        enter_registered_phone: "নিবন্ধিত ফোন নম্বর লিখুন",
        enter_new_password_placeholder: "নতুন পাসওয়ার্ড লিখুন",
        confirm_new_password_placeholder: "নতুন পাসওয়ার্ড নিশ্চিত করুন",
        terms_footer: "চালিয়ে যাওয়ার মাধ্যমে, আপনি আমাদের পরিষেবার শর্তাবলীতে সম্মত হচ্ছেন",
        // Subscription & Payment
        current_plan: "বর্তমান প্ল্যান",
        subscribe_now: "এখন সাবস্ক্রাইব করুন!",
        recommended_tag: "প্রস্তাবিত",
        premium_version: "প্রিমিয়াম সংস্করণ",
        select_payment: "পেমেন্ট পদ্ধতি নির্বাচন করুন",
        amount_to_pay: "পরিশোধের পরিমাণ: ₹৪৯",
        pay_via_upi: "UPI-এর মাধ্যমে পেমেন্ট করুন",
        upi_options: "GPay, PhonePe, Paytm, ইত্যাদি",
        credit_debit_card: "ক্রেডিট / ডেবিট কার্ড",
        card_options: "Visa, Mastercard, RuPay",
        netbanking: "নেটব্যাংকিং",
        netbanking_options: "সমস্ত প্রধান ভারতীয় ব্যাংক",
        back_btn: "ফিরে যান",
        waiting_upi: "UPI অ্যাপের জন্য অপেক্ষা করা হচ্ছে...",
        complete_payment_msg: "অনুগ্রহ করে আপনার ফোন চেক করুন এবং ₹৪৯ পেমেন্ট সম্পূর্ণ করুন।",
        cancel_request: "অনুরোধ বাতিল করুন",
        payment_successful: "পেমেন্ট সফল!",
        premium_activated: "আপনার প্রিমিয়াম সাবস্ক্রিপশন এখন সক্রিয়। সমস্ত বৈশিষ্ট্য আনলক করা হয়েছে।",
        continue_dashboard: "ড্যাশবোর্ডে চালিয়ে যান",
        per_month: "/মাস",
        // Marketplace Extras
        digital_agri_portal: "ডিজিটাল এগ্রি-ইন্ডিয়া পোর্টাল",
        welcome_marketplace: "মার্কেটপ্লেসে স্বাগতম",
        select_role_continue: "চালিয়ে যেতে অনুগ্রহ করে আপনার ভূমিকা নির্বাচন করুন",
        i_am_buyer: "আমি একজন ক্রেতা",
        browse_contact_farmers: "কৃষকদের ব্রাউজ করুন এবং সরাসরি যোগাযোগ করুন",
        i_am_farmer: "আমি একজন কৃষক",
        list_manage_produce: "আপনার পণ্য তালিকাভুক্ত করুন এবং পরিচালনা করুন",
        agri_marketplace: "কৃষি মার্কেটপ্লেস",
        marketplace_hero_desc: "সরাসরি বাণিজ্য এবং প্রিমিয়াম মার্কেট অ্যাক্সেসের মাধ্যমে ভারতীয় কৃষকদের ক্ষমতায়ন",
        publish_listing: "লিস্টিং প্রকাশ করুন",
        my_active_listings: "আমার সক্রিয় লিস্টিং",
        listings_appear_here: "আপনার প্রকাশিত লিস্টিং এখানে উপস্থিত হবে",
        location_map_label: "অবস্থান (Google Maps লিঙ্ক)",
        paste_map_link: "ম্যাপ লিঙ্ক পেস্ট করুন বা জিপিএস পান",
        whatsapp_number: "WhatsApp নম্বর",
        ten_digit_placeholder: "১০-সংখ্যার নম্বর",
        select_state: "রাজ্য নির্বাচন করুন",
        select_district: "জেলা নির্বাচন করুন",
        enter_village_area: "গ্রাম বা এলাকার নাম লিখুন",
        // Cart & Checkout
        my_cart: "আমার কার্ট",
        your_cart_empty: "আপনার কার্ট খালি",
        add_items_begin: "শুরু করতে মার্কেটপ্লেস থেকে আইটেম যোগ করুন",
        total_label: "মোট",
        proceed_checkout: "চেকআউটে এগিয়ে যান",
        secure_checkout: "নিরাপদ চেকআউট",
        order_summary: "অর্ডার সারাংশ",
        subtotal: "উপমোট",
        delivery: "ডেলিভারি",
        direct_from_farmer: "সরাসরি কৃষকের কাছ থেকে",
        your_details: "আপনার বিবরণ",
        your_full_name: "আপনার পুরো নাম",
        your_whatsapp: "আপনার WhatsApp নম্বর",
        delivery_address: "ডেলিভারি ঠিকানা (ঐচ্ছিক)",
        village_city_pin: "গ্রাম / শহর / পিনকোড",
        order_whatsapp_note: "আপনার অর্ডার WhatsApp-এর মাধ্যমে প্রতিটি কৃষকের কাছে পাঠানো হবে। তারা প্রাপ্যতা নিশ্চিত করবে এবং সরাসরি ডেলিভারির ব্যবস্থা করবে।",
        send_order_whatsapp: "WhatsApp-এর মাধ্যমে অর্ডার পাঠান",
        // Profile
        farming_statistics: "কৃষি পরিসংখ্যান",
        leaf_scans_stat: "পাতা স্ক্যান",
        weather_checks_stat: "আবহাওয়া চেক",
        calculations_stat: "হিসাব",
        crops_tracked_stat: "ট্র্যাক করা ফসল",
        farming_history: "কৃষি ইতিহাস",
        export_pdf: "পিডিএফ রপ্তানি করুন",
        all_activities: "সমস্ত ক্রিয়াকলাপ",
        scans_filter: "স্কैन",
        weather_filter: "আবহাওয়া",
        calculations_filter: "হিসাব",
        crops_filter: "ফসল",
        no_activities_yet: "এখনও কোনও কার্যকলাপ নেই। আপনার কৃষি ইতিহাস দেখতে ভারতফার্ম ব্যবহার শুরু করুন!",
        preferences_title: "পছন্দসমূহ",
        preferred_crops: "পছন্দের ফসল",
        none_selected: "কিছুই নির্বাচিত হয়নি",
        not_set: "সেট করা হয়নি",
        edit_label: "সম্পাদনা করুন",
        save_label: "সংরক্ষণ করুন",
        cancel_label: "বাতিল করুন",
        // Scanner Extras
        scanner_full_desc: "রোগ নির্ণয় করতে এবং সারের সুপারিশ পেতে যেকোনো গাছের পাতার একটি ছবি আপলোড বা ক্যাপচার করুন।",
        supports_formats: "সমর্থিত: JPG, PNG, WEBP",
        open_camera: "ক্যামেরা খুলুন",
        take_photo_title: "ছবি তুলুন",
        capture_btn: "ক্যাপচার করুন",
        retake_btn: "পুনরায় তুলুন",
        use_photo_btn: "ছবি ব্যবহার করুন",
        analysis_result: "বিশ্লেষণের ফলাফল",
        plant_status: "উদ্ভিদের অবস্থা",
        desc_appear_here: "বিবরণ এখানে উপস্থিত হবে।",
        // Weather Extras
        enter_village_city: "গ্রাম বা শহরের নাম লিখুন",
        refresh_btn: "রিফ্রেশ করুন",
        offline_note: "আপনি অফলাইনে আছেন। উপলব্ধ হলে ক্যাশ করা আবহাওয়া দেখানো হবে।",
        fetching_weather: "আবহাওয়ার ডেটা আনা হচ্ছে...",
        safe_farming_title: "কৃষিকাজের জন্য নিরাপদ",
        what_to_do: "কী করবেন",
        what_not_to_do: "কী করবেন না",
        ai_farming_advice: "এআই কৃষি পরামর্শ",
        generating_advice: "পরামর্শ তৈরি করা হচ্ছে...",
        // Calculator Extras
        cost_only_note: "শুধুমাত্র বীজ এবং সারের খরচ। শ্রম, সরঞ্জাম অন্তর্ভুক্ত নয়।",
        search_type_crop: "-- খুঁজুন বা ফসলের নাম লিখুন --",
        please_valid_crop: "অনুগ্রহ করে একটি বৈধ ফসল লিখুন",
        acre_unit: "একর",
        bigha_unit: "বিঘা",
        katha_unit: "কাঠা",
        unit_conversion_info: "১ বিঘা = ২০ কাঠা | ১ বিঘা ≈ ০.৬২ একর | ১ একর ≈ ৩২.২৬ কাঠা",
        acres_label: "একর",
        enter_land_size_ph: "জমির আকার লিখুন",
        calculate_total_cost: "মোট খরচ হিসাব করুন",
        required_seed_qty: "প্রয়োজনীয় বীজের পরিমাণ",
        total_seed_cost: "মোট বীজের খরচ",
        required_fert_qty: "প্রয়োজনীয় সারের পরিমাণ",
        total_fert_cost: "মোট সারের খরচ",
        total_farming_input: "মোট কৃষি ইনপুট খরচ",
        // Roadmap Extras
        farming_activity_roadmap: "কৃষি কার্যকলাপ রোডম্যাপ",
        select_crop_schedule: "বিস্তারিত কার্যকলাপের সময়সূচী দেখতে একটি ফসল নির্বাচন করুন",
        please_select_first: "অনুগ্রহ করে প্রথমে একটি ফসল নির্বাচন করুন।",
        select_a_crop_btn: "একটি ফসল নির্বাচন করুন",
        start_farming_session: "কৃষি সেশন শুরু করুন",
        end_session: "সেশন শেষ করুন",
        // Wiki
        ai_knowledge_base: "এআই-চালিত নলেজ বেস",
        crop_health_wiki: "ফসল স্বাস্থ্য উইকি",
        wiki_desc: "উদ্ভিদের রোগ, কীটপতঙ্গ এবং মাটির স্বাস্থ্যের জন্য ব্যাপক জ্ঞানভান্ডার",
        search_diseases_crops: "রোগ, ফসল খুঁজুন...",
        all_wiki: "সমস্ত",
        plant_wiki: "উদ্ভিদ",
        pest_wiki: "কীটপতঙ্গ",
        soil_wiki: "মাটি",
        loading_disease_db: "রোগের ডেটাবেস লোড হচ্ছে...",
        // Footer
        footer_brand_desc: "এআই-চালিত ফসলের অন্তর্দৃষ্টি, রোগ নির্ণয় এবং সরাসরি মার্কেটপ্লেস অ্যাক্সেস দিয়ে ভারতীয় কৃষকদের ক্ষমতায়নের বুদ্ধিমান স্মার্ট ফার্মিং প্ল্যাটফর্ম।",
        footer_platform: "প্ল্যাটফর্ম",
        footer_home: "হোম",
        footer_farmer_app: "কৃষক অ্যাপ",
        footer_pricing: "মূল্য নির্ধারণ প্ল্যান",
        footer_other_links: "অন্যান্য লিঙ্ক",
        footer_disclaimer: "দাবিত্যাগ",
        footer_faq: "প্রায়শই জিজ্ঞাসিত প্রশ্ন",
        footer_ai_method: "এআই পদ্ধতি",
        footer_legal: "আইনি",
        footer_terms: "শর্তাবলী",
        footer_privacy: "গোপনীয়তা নীতি",
        footer_data_protection: "ডেটা সুরক্ষা",
        footer_accessibility: "অ্যাক্সেসযোগ্যতা",
        footer_about: "সম্পর্কে",
        footer_about_section: "আমাদের সম্পর্কে",
        footer_last_updated: "শেষ আপডেট: ১৬-০৩-২০২৬",
        footer_copyright: "© ২০২৬ ভারত ফার্ম। ভারতীয় কৃষির ক্ষমতায়ন।",
        // Bottom Nav
        nav_home: "হোম",
        nav_weather: "আবহাওয়া",
        nav_market: "মার্কেট",
        nav_about: "সম্পর্কে",
        nav_crops: "ফসল",
        nav_wiki: "উইকি",
        nav_quiz: "কুইজ",
        nav_calc: "হিসাব",
        // About Page
        about_tagline: "স্মার্ট এগ্রিকালচার প্ল্যাটফর্ম",
        about_heading: "ভারতফার্ম সম্পর্কে",
        about_desc: "ভারতফার্ম একটি ব্যাপক ওয়েব অ্যাপ্লিকেশন যা ভারতীয় কৃষকদের আধুনিক প্রযুক্তি এবং ডেটা-চালিত অন্তর্দৃষ্টি দিয়ে ক্ষমতায়নের জন্য ডিজাইন করা হয়েছে। আমাদের প্ল্যাটফর্ম কৃষকদের আরও ভালো সিদ্ধান্ত নিতে এবং উৎপাদনশীলতা বাড়াতে সাহায্য করার জন্য ফসল পরিকল্পনা, রোগ নির্ণয়, আবহাওয়া পর্যবেক্ষণ এবং আর্থিক পরিকল্পনার জন্য বুদ্ধিমান সরঞ্জাম সরবরাহ করে।",
        key_features_title: "প্রধান বৈশিষ্ট্য",
        ai_assistant_title: "এআই কৃষি সহকারী",
        ai_assistant_desc: "ব্যক্তিগতকৃত কৃষি বিশেষজ্ঞের পরামর্শের জন্য ২৪/৭ স্মার্ট চ্যাটবট",
        smart_market_about: "স্মার্ট মার্কেটপ্লেস",
        smart_market_about_desc: "বীজ, সরঞ্জাম এবং সারের জন্য সমন্বিত ই-কমার্স পোর্টাল",
        ai_scanner_about: "এআই রোগ স্ক্যানার",
        ai_scanner_about_desc: "ফসলের স্বাস্থ্য এবং রোগের জন্য উন্নত জেমিনি-চালিত নির্ণয়",
        weather_monitor_about: "আবহাওয়া পর্যবেক্ষণ",
        weather_monitor_about_desc: "স্মার্ট সুরক্ষা সতর্কতা সহ রিয়েল-টাইম স্থানীয় আবহাওয়ার ডেটা",
        cost_calc_about: "খরচ ক্যালকুলেটর",
        cost_calc_about_desc: "ফসল বিনিয়োগ এবং লাভের জন্য এআই-বর্ধিত আর্থিক পরিকল্পনা",
        activity_roadmap_about: "কার্যকলাপ রোডম্যাপ",
        activity_roadmap_about_desc: "অনুকূলিত চাষের জন্য বুদ্ধিমান প্রতিদিনের সময়সূচী",
        dev_team: "উন্নয়ন দল",
        team_intro_text: "ভারতফার্ম ভারতীয় কৃষিকে সমর্থন করার জন্য প্রযুক্তির ব্যবহার সম্পর্কে উত্সাহী শিক্ষার্থীদের একটি নিবেদিত দল দ্বারা তৈরি করা হয়েছিল:",
        lead_dev: "প্রধান বিকাশকারী",
        full_stack_dev: "ফুল স্ট্যাক ডেভেলপার",
        backend_dev: "ব্যাকএন্ড ডেভেলপার",
        frontend_dev: "ফ্রন্টএন্ড ডেভেলপার",
        connect_btn: "সংযোগ করুন",
        our_mission: "আমাদের লক্ষ্য",
        mission_desc: "ঐতিহ্যবাহী চাষাবাদ পদ্ধতি এবং আধুনিক প্রযুক্তির মধ্যে ব্যবধান দূর করা, উন্নত কৃষি সরঞ্জামগুলি ভারতের প্রতিটি কৃষকের কাছে অ্যাক্সেসযোগ্য করে তোলা। আমরা বিশ্বাস করি যে সঠিক তথ্য এবং সরঞ্জামের সাহায্যে, কৃষকরা তাদের ফলন উল্লেখযোগ্যভাবে উন্নত করতে, খরচ কমাতে এবং আরও তথ্যসম্মত সিদ্ধান্ত নিতে পারে।",
        all_rights: "© ২০২৬ ভারতফার্ম - সর্বস্বত্ব সংরক্ষিত",
        made_with_love: "ভারতীয় কৃষকদের জন্য ❤ দিয়ে তৈরি",
        // Schemes Extras
        scheme_matchmaker_title: "স্কিম ম্যাচমেকার",
        find_govt_schemes_desc: "আপনি যে সরকারি কৃষি প্রকল্পগুলির জন্য যোগ্য তা খুঁজুন",
        land_details_title: "জমির বিবরণ",
        how_much_land: "আপনার কতটুকু চাষযোগ্য জমি আছে? (একরে)",
        landless_note: "আপনি যদি ভূমিহীন কৃষক বা ভাগচাষী হন তবে 0 লিখুন।",
        location_step_title: "অবস্থান",
        crop_info_step_title: "ফসলের তথ্য",
        primary_crop_q: "আপনার প্রধান ফসল কী? (ঐচ্ছিক)",
        searching_text: "খোঁজা হচ্ছে...",
        check_another: "অন্য প্রোফাইল পরীক্ষা করুন",
        matched_text: "মেলেছে",
        // Dashboard Extras
        dash_activity_desc: "সঠিক ফসলের জীবনচক্র এবং হাইপার-লোকাল ডেটার উপর ভিত্তি করে স্মার্ট টাস্ক শিডিউলিং।",
        open_roadmap_cta: "রোডম্যাপ খুলুন",
        dash_weather_desc: "আপনার ফলন রক্ষা করতে রিয়েল-টাইম হাইপার-লোকাল আবহাওয়া ট্র্যাকিং।",
        view_forecast: "পূর্বাভাস দেখুন",
        dash_wiki_title: "ফসল স্বাস্থ্য উইকি",
        dash_wiki_desc: "উদ্ভিদের রোগ, কীটপতঙ্গ এবং মাটির স্বাস্থ্যের জন্য এআই-চালিত বিশ্বকোষ।",
        open_wiki: "উইকি খুলুন",
        // Session Dashboard
        current_session: "বর্তমান কৃষি সেশন",
        session_crop: "ফसल",
        session_started: "শুরু হয়েছে",
        session_input_cost: "ইনপুট খরচ",
        session_revenue: "রাজস্ব",
        // Quiz
        loading_question: "প্রশ্ন লোড হচ্ছে..."
    }
};

// ============================================
// INITIALIZE LANGUAGE SYSTEM
// ============================================
document.addEventListener('DOMContentLoaded', function() {
    // Check if language is already selected
    const selectedLang = localStorage.getItem('bharatfarm_language');
    
    if (!selectedLang) {
        // First-time user - show language modal
        showLanguageModal();
    } else {
        // Apply saved language
        currentLanguage = selectedLang;
        translatePage();
    }
});

// ============================================
// CORE TRANSLATION HELPERS
// ============================================

/**
 * Returns the translated string for a given key.
 * If the key is not found in the current language, falls back to English.
 * If not found in English, returns the key itself.
 */
function t(key) {
    if (translations[currentLanguage] && translations[currentLanguage][key]) {
        return translations[currentLanguage][key];
    }
    // Fallback to English
    if (translations['en'] && translations['en'][key]) {
        return translations['en'][key];
    }
    // Final fallback: return the key itself
    return key;
}

/**
 * Scans the DOM for elements with 'data-i18n' attribute
 * and updates their textContent or placeholder.
 */
function translatePage() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        const translatedText = t(key);
        
        // Handle placeholders for input/textarea
        if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
            if (el.type === 'submit' || el.type === 'button') {
                 el.value = translatedText;
            } else {
                 el.placeholder = translatedText;
            }
        } 
        // Handle tooltips or titles
        else if (el.hasAttribute('title')) {
            el.setAttribute('title', translatedText);
        }
        // Special case for elements containing icons AND text
        else if (el.children.length > 0 && el.innerHTML.includes('<i class=')) {
            // Usually, icon is the first child. Let's keep the icon and replace the text node
            // A simple approach is to extract the icon HTML, then append the text
            const iconHtml = el.querySelector('i') ? el.querySelector('i').outerHTML : '';
            // If the element relies on specific internal structure, you might need fine-tuning.
            // For general cases where it's just <i class="..."></i> Text
            el.innerHTML = iconHtml + ' ' + translatedText;
        }
        // Standard text replacement
        else {
            el.textContent = translatedText;
        }
    });

    // Notify other dynamic components to refresh their localized content
    refreshDynamicContent();
}

/**
 * Sets the active language, updates local storage, and translates the page.
 */
function setLanguage(lang) {
    if (!translations[lang]) {
        console.error(`Language ${lang} not supported.`);
        return;
    }
    currentLanguage = lang;
    localStorage.setItem('bharatfarm_language', lang);
    
    // Immediately translate static HTML elements
    translatePage();
    
    // Close modal if open
    closeLanguageModal();
}

/**
 * Calls re-render functions for dynamic sections (e.g. Weather, Roadmap, Marketplace)
 * that generate HTML on the fly.
 */
function refreshDynamicContent() {
    // Dispatch a custom event that other scripts can listen to
    const event = new CustomEvent('languageChanged', { detail: { language: currentLanguage } });
    document.dispatchEvent(event);
    
    // Fallback for direct global function calls if they exist to re-render dynamic content
    if (typeof updateDashboard === 'function') {
        try { updateDashboard(); } catch (e) {}
    }
    if (typeof fetchCrops === 'function') {
        try { fetchCrops(); } catch (e) {}
    }
}

// ============================================
// SHOW/HIDE LANGUAGE MODAL
// ============================================
function showLanguageModal() {
    const modal = document.getElementById('languageModal');
    if (modal) {
        modal.classList.add('active');
    }
}

function closeLanguageModal() {
    const modal = document.getElementById('languageModal');
    if (modal) {
        modal.classList.remove('active');
    }
}

// ============================================
// MAKE FUNCTIONS GLOBALLY ACCESSIBLE
// ============================================
window.t = t;
window.translatePage = translatePage;
window.setLanguage = setLanguage;
window.currentLanguage = currentLanguage;
window.translations = translations;
window.selectLanguage = setLanguage; // Alias for backward compatibility with onclick="selectLanguage('bn')"
window.showLanguageModal = showLanguageModal;
window.closeLanguageModal = closeLanguageModal;

// Re-render Dynamic Content on Language Change
document.addEventListener('languageChanged', () => {
    // Re-render marketplace or other sections if needed
    if (typeof renderWikiGrid === 'function' && typeof wikiData !== 'undefined') {
        try { renderWikiGrid(wikiData); } catch (e) {}
    }
    // Update weather UI text
    if (typeof updateWeatherUI === 'function' && typeof userLocationName !== 'undefined') {
        try { updateWeatherUI(userLocationName); } catch(e) {}
    }
});
